[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-cluster-manager"
version = "0.1.5"
description = "Admin dashboard + satellite clients for multi-model vLLM deployments"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [{name = "Marc Schlichting", email="mschl@stanford.edu"}]
urls = {Hompage="https://github.com/sisl/VLLMClusterManager"}

[project.scripts]
vllm-cluster-manager = "vllm_cluster_manager.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["vllm_cluster_manager*"]

[tool.setuptools.package-data]
"vllm_cluster_manager" = ["assets/**"]
